[project]
name = "user_service"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "asgiref==3.11.0",
    "celery==5.4.0",
    "attrs==25.4.0",
    "certifi==2025.11.12",
    "cffi==2.0.0",
    "cfgv==3.5.0",
    "charset-normalizer==3.4.4",
    "cryptography==46.0.3",
    "defusedxml==0.7.1",
    "distlib==0.4.0",
    "django==5.2.9",
    "django-filter==25.2",
    "django-redis==6.0.0",
    "djangorestframework==3.16.1",
    "djangorestframework-simplejwt==5.5.1",
    "djoser==2.3.3",
    "drf-spectacular==0.29.0",
    "filelock==3.20.1",
    "gunicorn==23.0.0",
    "identify==2.6.15",
    "idna==3.11",
    "inflection==0.5.1",
    "jsonschema==4.26.0",
    "jsonschema-specifications==2025.9.1",
    "nodeenv==1.10.0",
    "oauthlib==3.3.1",
    "packaging==25.0",
    "platformdirs==4.5.1",
    "psycopg2==2.9.11",
    "pycparser==2.23",
    "pyjwt==2.10.1",
    "python3-openid==3.2.0",
    "pyyaml==6.0.3",
    "redis==7.1.0",
    "referencing==0.37.0",
    "requests==2.32.5",
    "requests-oauthlib==2.0.0",
    "rpds-py==0.30.0",
    "social-auth-app-django==5.7.0",
    "social-auth-core==4.8.3",
    "sqlparse==0.5.5",
    "typing-extensions==4.15.0",
    "uritemplate==4.2.0",
    "urllib3==2.6.2",
    "virtualenv==20.35.4",
]

[dependency-groups]
dev = [
    "ruff>=0.14.8",
    "pre-commit==4.5.1",
]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 120
indent-width = 4

target-version = "py313"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"

indent-style = "space"

skip-magic-trailing-comma = false

line-ending = "auto"

docstring-code-format = false

docstring-code-line-length = "dynamic"
