# Generated by Django 5.2.9 on 2026-01-15 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_group_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
